[package]
name = "js_beautify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettify-js = "0.1.0"
pyo3 = { version = "0.18.3", features = ["extension-module"] }

[lib]
name = "js_beautify"